---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: openshift-backup
  labels:
    app: openshift-backup
spec:
  schedule: "56 23 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    metadata:
      labels:
        app: openshift-backup
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: openshift-backup
        spec:
          containers:
            - name: etcd-backup
              image: ocp-cli
              command:
                - "/bin/bash"
                - "-c"
                - >
                  oc get no -l node-role.kubernetes.io/master --no-headers -o name | xargs -I {} -- oc debug {} -- bash -c 
                  'chroot /host sudo -E /usr/local/bin/cluster-backup.sh /home/core/backup/ && 
                  chroot /host sudo -E find /home/core/backup/ -type f -mtime +"3" -delete'
          restartPolicy: "Never"
          terminationGracePeriodSeconds: 30
          activeDeadlineSeconds: 500
          dnsPolicy: "ClusterFirst"
          serviceAccountName: "openshift-backup"
          serviceAccount: "openshift-backup"
