apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ocp-etcd-backup

resources:
- namespace.yml
- etcd-bck-sa.yml
- etcd-bck-clusterRoleBinding.yml
- etcd-bck-sccClusterRoleBinding.yml
- etcd-bck-clusterRole.yml
- etcd-bck-cronJob.yml

images:
- name: ocp-cli
  newName: registry.redhat.io/openshift4/ose-cli
  newTag: v4.11
