apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ocp-etcd-backup

resources:
- project.yml

patchesJson6902:
- target:
    group: security.openshift.io
    version: v1
    kind: SecurityContextConstraints
    name: privileged
  path: jsonPatch.yml
