apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ocp-etcd-backup

resources:
- namespace.yml
- etcd-bck-sa.yml
- etcd-bck-clusterRoleBinding.yml
- etcd-bck-clusterRole.yml
- etcd-bck-cronJob.yml

patchesJson6902:
- target:
    group: security.openshift.io
    version: v1
    kind: SecurityContextConstraints
    name: privileged
  path: jsonPatch.yml

images:
- name: ocp-cli
  newName: registry.redhat.io/openshift4/ose-cli
  newTag: v4.11
