---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: "Openshift Backup Automation Tool"
    openshift.io/display-name: "Backup ETCD Automation"
  name: ocp-etcd-backup
